import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
  <head>
   
   <title>Sportz — Colorlib Sports Team Template</title>
   <meta charSet="utf-8" />
   <meta
     name="viewport"
     content="width=device-width, initial-scale=1, shrink-to-fit=no"
   />
   <link
     rel="stylesheet"
     href="https://fonts.googleapis.com/css?family=Mukta:300,400,700"
   />
   <link rel="stylesheet" href="fonts/icomoon/style.css" />
   <link rel="stylesheet" href="css/bootstrap.min.css" />
   <link rel="stylesheet" href="css/magnific-popup.css" />
   <link rel="stylesheet" href="css/jquery-ui.css" />
   <link rel="stylesheet" href="css/owl.carousel.min.css" />
   <link rel="stylesheet" href="css/owl.theme.default.min.css" />
   <link rel="stylesheet" href="css/aos.css" />
   <link rel="stylesheet" href="/css/style.css" />
 
       </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        <Script src="js/jquery-3.3.1.min.js"></Script>
  <Script src="js/jquery-migrate-3.0.1.min.js"></Script>
  <Script src="js/jquery-ui.js"></Script>
  <Script src="js/popper.min.js"></Script>
  <Script src="js/bootstrap.min.js"></Script>
  <Script src="js/owl.carousel.min.js"></Script>
  <Script src="js/jquery.stellar.min.js"></Script>
  <Script src="js/jquery.countdown.min.js"></Script>
  <Script src="js/jquery.magnific-popup.min.js"></Script>
  <Script src="js/aos.js"></Script>

  <Script src="js/main.js"></Script>
      </body>
    </html>
  );
}
